name: Main Workflow

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.x

        - name: Install dependencies
          run: pip install -r requirements.txt

        # - name: Run tests
        #   run: pytest

        - name: Lint code
          run: pylint --rcfile .pylintrc --fail-under=8.0 src/main.py

        - name: Build executable
          run: pyinstaller --onefile src/main.py -n mc_server_controller

        # - name: Move executable to dist folder
        #   run: mv dist/your_python_file /path/to/your/repo/dist/

        - name: Commit and push changes
          uses: EndBug/add-and-commit@v7
          with:
            author_name: GitHub Actions
            author_email: actions@github.com
            message: Add generated executable
            add: 'dist/mc_server_controller'
            push: true

            