name: Python App Workflow

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.x

        - name: Install dependencies
          run: pip install -r requirements.txt

        - name: Run tests
          run: pytest

        - name: Lint code
          run: pylint your_python_file.py

        - name: Build executable
          run: pyinstaller --onefile your_python_file.py

        - name: Move executable to dist folder
          run: mv dist/your_python_file /path/to/your/repo/dist/

        - name: Commit changes
          run: |
                git config --global user.name "Your Name"
                git config --global user.email "your-email@example.com"
                git add .
                git commit -m "Add executable to dist folder"
                git push